name: xeus-cookiecutter

channels:
  - conda-forge
dependencies:
  - cookiecutter
  - make
  - cmake
  - python >=3.6
  - cookiecutter
  - pytest-cookies
  - pytest
  - xeus-zmq >=1.0.2,<2.0
  - xtl
  - sh
  - nlohmann_json
  - cppzmq
  - pytest-rerunfailures
